### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by fmoessle** [qdouble/angular-webpack-starter#236]
Since Universal still isn't an option, maybe a Service Worker could improve loading time.

Google provides a module called Service Worker Precache, which you can find here:
[https://github.com/GoogleChrome/sw-precache](url)

It could be added to the webpack build process.

**Comment by qdouble** [comment]
I'll look into this... just starting to experiment with service workers now.

**Comment by qdouble** [comment]
I'm going to add this and push notifications in a few days, I'm already running it on my project, just want to be sure about the configuration before adding it to this starter. I'll probably also advise people in the readme to not to use the universal branches until Universal migrates over to core and angular 4 is released and stop updating those branches until then.

**Comment by qdouble** [comment]
I'll leave people to add this themselves. Precache has a lot of drawbacks and I've stopped using it as it's very easy for clients to be stuck with a corrupt version of your site or for their browser to keep loading an old version of your site after you've made updates.
