### ISSUE TITLE
Can you rename the repository?

### ISSUE THREAD

**Issue by splincode** [qdouble/angular-webpack-starter#319]
Rename `angular-webpack2-starter` to `angular-webpack-starter`. Because you usage webpack 3.0.

Github stores links to repository names, if people go to https://github.com/qdouble/angular-webpack2-starter, the Github will redirect to https://github.com/qdouble/angular-webpack-starter

**Comment by junibrosas** [comment]
Rename it into something that sounds like a brand. :)

**Comment by qdouble** [comment]
okay, I've renamed it
