### ISSUE TITLE
Typescript source maps

### ISSUE THREAD

**Issue by leqwasd** [qdouble/angular-webpack-starter#325]
Source maps are not working with this configuration (out of the box): 

    exports.DEV_SOURCE_MAPS = 'eval';

It works with this tho:

    exports.DEV_SOURCE_MAPS = 'source-map';

Just noting - maybe you should modify default configuration to do what is is suppose to do :)

**Comment by antonpegov** [comment]
@leqwasd Thank you man!!!

**Comment by qdouble** [comment]
Changed the default here: https://github.com/qdouble/angular-webpack-starter/commit/2d7e152e042807ec2751bea840e571519728154b
