### ISSUE TITLE
Ability to skip bundle analysis for CI prod builds

### ISSUE THREAD

**Issue by Aigeec** [qdouble/angular-webpack-starter#329]
It would be great to be able to skip the bundle analysis in cases where you are doing use an automated build tool such as travis or jenkins.

Could you add a constant or env parameter to optionally disable it e.g.

```javascript
if (!E2E && !WATCH && ANALYZE_BUNDLE) {
  config.plugins.push(
    new BundleAnalyzerPlugin({ analyzerPort: 5000 })
  );
}
```

**Comment by qdouble** [comment]
@Aigeec it's a constant already: https://github.com/qdouble/angular-webpack-starter/blob/master/constants.js#L11
https://github.com/qdouble/angular-webpack-starter/blob/master/webpack.config.ts#L219

Are you looking for it to be a npm flag?
