### ISSUE TITLE
Getting error running Universal out of the box

### ISSUE THREAD

**Issue by dvaldivia** [qdouble/angular-webpack-starter#332]
Hi, I just clones the repository and I was able to start the application with `yarn start` and play with it, however when I tried `yarn run universal` I get the following error:

```
PRODUCTION BUILD:  true
AOT:  false
BUILDING UNIVERSAL
  0% compiling
/Users/dvaldivia/angular-webpack-starter/node_modules/script-ext-html-webpack-plugin/lib/plugin.js:50
      compilation.hooks.htmlWebpackPluginAlterAssetTags.tap(PLUGIN, alterAssetTags);
                                                        ^
TypeError: Cannot read property 'tap' of undefined
```

however `yarn run universal:aot` does run fine

**Comment by qdouble** [comment]
Should be fixed with my latest commit. I removed the script-ext-html-webpack-plugin as it wasn't really being used anyway.

**Comment by dewang** [comment]
Cheers. I can confirm that it now works
